#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("com.amazon.sample.buttonclicker.Resource", IsApplication=true)]

namespace com.amazon.sample.buttonclicker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bluebutton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bluebuttonup = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int buttonbluedown = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int buttongreendown = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int buttongreenup = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int buttonpurpledown = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int buttonpurpleup = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int buttonreddown = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int buttonredup = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int greenbutton = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int purchasebuttonbuymore = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int purplebutton = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int redbutton = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int swatchblue = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int swatchbluelocked = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int swatchgreen = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int swatchgreenlocked = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int swatchpurple = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int swatchpurplelocked = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int swatchred = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int textclicksleft = 2130837525;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int blueswatch = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int button = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int buyClicks = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int greenswatch = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout2 = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int main = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int numClicks = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int purpleswatch = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int redswatch = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int tableLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int tableRow1 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int textView1 = 2131034117;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int child_subscription_sku_monthly = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int consumable_sku = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int entitlement_sku_blue = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int entitlement_sku_green = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int entitlement_sku_purple = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int nothing = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int parent_subscription_sku = 2130968582;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
